blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/
    about: Join our Discord server for support and updates.
  - name: Telegram group
    url: https://t.me/saikou_discussion
    about: Join our Telegram discussion group for support and updates.
